# This is a basic workflow to demonstrate using GitHub Actions secrets

name: CI with Secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Access a secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: Use secret in script
        run: |
          if [ "$SECRET_FROM_ENV" == "mySecretValue" ]; then
            echo "Secret matches expected value!"
          else
            echo "Secret does not match."
          fi
        env:
          SECRET_FROM_ENV: ${{ secrets.MY_SECRET }}
